### ISSUE TITLE
Cannot delete?

### ISSUE THREAD

**Issue by kutchar** [jhc-systems/sqlest#24]
I just came across the following line in the code base:
https://github.com/jhc-systems/sqlest/blob/master/sqlest/src/main/scala/sqlest/executor/Database.scala#L106

Does this mean sqlest cannot delete records?

**Comment by hamishdickson** [comment]
Hi @kutchar very well spotted and thanks for looking into this. It's actually been resolved by pull request #19 which is just waiting to be merged
