### ISSUE TITLE
Possible to produce SQL which is invalid on DB2

### ISSUE THREAD

**Issue by DavidGregory084** [jhc-systems/sqlest#33]
sqlest allows use of queries which join tables on `LiteralColumn[Boolean]` / `ConstantColumn[Boolean]`. This would be valid in some database engines, but in DB2:

```sql
select *                
from client             
inner join matter on 1=1
```

...is valid SQL, but:

```sql
select *                 
from client              
inner join matter on true
```

...is not.

This is an easy mistake to make as this kind of condition could be created when a developer forgets to use the triple equals `===` and uses `==` instead.

**Comment by DavidGregory084** [comment]
Not sure what the answer is in this case; perhaps we could alter the DB2 statement builder to create dummy boolean conditions like 1=1.

**Comment by hamishdickson** [comment]
That's pretty difficult and I personally wouldn't like to see it restricted

Have you thought about a compile time warning?

**Comment by DavidGregory084** [comment]
The only annotations that I know of which produce compile-time warnings with custom messages are `@implicitNotFound` and `@deprecated`, so it's certainly possible but might be a bit awkward / annoying for the user?

**Comment by DavidGregory084** [comment]
Might be of use as an overloaded "on" method for those column types?: [Scala: Custom compiler warning](http://stackoverflow.com/questions/22284932/scala-custom-compiler-warning)

**Comment by DavidGregory084** [comment]
This problem is also apparent when trying to define where clauses that rely on boolean literals:

```scala
case class Code(code: String)

val someCode = Code("")

select
      .from(Table)
      .where(
        Table.code === someCode ||
         someCode.code.isEmpty
      )
```
