### ISSUE TITLE
Optional LocalDate columns don't work as expected in where clause

### ISSUE THREAD

**Issue by nico78** [jhc-systems/sqlest#44]
If I define an optional date column based on an "integer date" field:
```scala
val expiryDate = column[Option[LocalDate]]("expDt")(ZeroIsNoneColumnType(YyyyMmDdColumnType))
```
then trying to select rows from the table where the expiry date is zero or in the future:

```scala
   .where(myTable.expiryDate === None ||  myTable.expiryDate > LocalDate.now)
```
..doesn't typecheck:

> found   : None.type
> [error]  required: sqlest.ast.Column[?]

This  workaround works though:

```scala
   .where(myTable.expiryDate === None.column(ZeroIsNoneColumnType(YyyyMmDdColumnType)) ||
          myTable.expiryDate > LocalDate.now.column(YyyyMmDdColumnType))
```

**Comment by DavidGregory084** [comment]
Are you able to use Option.empty[LocalDate]?

**Comment by nico78** [comment]
No - it compiles but you get a ClassCastException at runtime

> scala.None$ cannot be cast to org.joda.time.LocalDate

**Comment by DavidGregory084** [comment]
Adding the following test to ExecutorSpec illustrates this issue:
```scala
"mapped optional value comparisons" should "execute correctly" in {
  select(TableSix.zeroIsNoneLocalDate)
    .from(TableSix)
    .where(TableSix.zeroIsNoneLocalDate === Option.empty[LocalDate])
}
```
I think this is because the `mapLiterals` method in `ColumnSyntax` assumes that comparisons will always be made to `Some`.
