### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by brendanator** [jhc-systems/sqlest#5]
There is a large amount of functionality in sqlest that is not documented anywhere. The examples project needs to be expanded to show this functionality in action

**Comment by hamishdickson** [comment]
Is most of this functionality under test? If so I can clean some of that up into examples for documentation

**Comment by brendanator** [comment]
It is under test
It would be great to turn it into some nice examples

**Comment by hamishdickson** [comment]
I'm having some issues getting delete to work - can you think why this delete example doesn't actually delete anything?

https://gist.github.com/hamishdickson/62d5426cce7040cab07e

**Comment by hamishdickson** [comment]
So I've had a quick debug and Database.execute delete does the following...

     def executeDelete(delete: Delete): Int = {
      checkInTransaction
      executeWithConnection { connection =>
        0
      }
    }

which doesn't look to be a great deal....

**Comment by hamishdickson** [comment]
Examples of aggregate functions created in pull request #34
