### ISSUE TITLE
order by on a union adds the order by in the wrong place

### ISSUE THREAD

**Issue by msillence** [jhc-systems/sqlest#53]
something of the form:
<pre>
select(MyTable.id)
      .from(
        select(1.constant.as("ordering"), MyTable.id)
          .from(MyTable)
		  .where(MyTable.x = x)
          .union(
            select(2.constant.as("ordering"), MyTable.id)
              .from(MyTable)
              .where(MyTable.y = x)
          ).orderBy(sqlest.ast.ReferenceColumn[Int]("ordering"))
		  ).as("combd")).fetchHeadOption
</pre>
Produces:
<pre>
select MYTABLE_id from
(
   select 1 as ordering, MYTABLE.id as MYTABLE_id
   from MYTABLE where (MYTABLE.x= ?)
   order by ordering
   union
   select 2 as ordering, MYTABLE.id as MYTABLE_id
   from MYTABLE where (MYTABLE.y= ?)
) as combd
</pre>
The order by should be at the end of the inner query:
<pre>
select MYTABLE_id from
(
   select 1 as ordering, MYTABLE.id as MYTABLE_id
   from MYTABLE where (MYTABLE.x= ?)
   union
   select 2 as ordering, MYTABLE.id as MYTABLE_id
   from MYTABLE where (MYTABLE.y= ?)
   order by ordering
) as combd
</pre>

**Comment by brendanator** [comment]
The orderBy is actually being put on the first select statement so this behaviour is correct - sqlest doesn't enforce the order of the clauses follows the sql spec (you could write select.where(...).from(...) for example)
All that is needed is to move the orderBy clause onto the inner query like so:
```scala
select(MyTable.id)
      .from(
        select(1.constant.as("ordering"), MyTable.id)
          .from(MyTable)
          .where(MyTable.x = x)
          .union(
            select(2.constant.as("ordering"), MyTable.id)
              .from(MyTable)
              .where(MyTable.y = x)
              .orderBy(sqlest.ast.ReferenceColumn[Int]("ordering"))
          )
          ).as("combd")).fetchHeadOption
```
